#!/usr/bin/env bash
# Generate the Homebrew formula for autocomplete-specs.
# Usage: generate-formula.sh <version> <sha256>
set -euo pipefail

VERSION="$1"
SHA256="$2"

cat <<EOF
# typed: false
# frozen_string_literal: true

# This file is generated by Okabe-Junya/autocomplete's release workflow. DO NOT EDIT.
class AutocompleteSpecs < Formula
  desc "Prebuilt completion specs for Kiro CLI autocomplete"
  homepage "https://github.com/Okabe-Junya/autocomplete"
  url "https://github.com/Okabe-Junya/autocomplete/releases/download/v${VERSION}/autocomplete-specs-${VERSION}.tar.gz"
  sha256 "${SHA256}"
  version "${VERSION}"
  license "MIT"

  def install
    pkgshare.install "build"
  end

  def post_install
    fig_dir = File.expand_path("~/.fig/autocomplete")
    target = File.join(fig_dir, "build")
    FileUtils.mkdir_p(fig_dir)
    if File.directory?(target) && !File.symlink?(target)
      backup = "#{target}.backup-#{Time.now.strftime("%Y%m%d%H%M%S")}"
      FileUtils.mv(target, backup)
      opoo "Existing #{target} moved to #{backup}"
    end
    FileUtils.ln_sf(opt_pkgshare/"build", target)
  end

  def caveats
    <<~EOS
      Completion specs are symlinked for Kiro CLI:
        ~/.fig/autocomplete/build -> #{opt_pkgshare}/build
      They update automatically on \`brew upgrade\`.
    EOS
  end

  test do
    assert_path_exists pkgshare/"build/kubectl.js"
  end
end
EOF
