#!/usr/bin/env node
// Generates Formula/autocomplete-specs.rb for Okabe-Junya/homebrew-tap.
// Usage: node scripts/generate-formula.mjs <version> <sha256>

export function generateFormula(version, sha256) {
  return `# typed: false
# frozen_string_literal: true

# This file is generated by Okabe-Junya/autocomplete's release workflow. DO NOT EDIT.
class AutocompleteSpecs < Formula
  desc "Prebuilt completion specs for Kiro CLI autocomplete"
  homepage "https://github.com/Okabe-Junya/autocomplete"
  url "https://github.com/Okabe-Junya/autocomplete/releases/download/v${version}/autocomplete-specs-${version}.tar.gz"
  sha256 "${sha256}"
  version "${version}"
  license "MIT"

  def install
    pkgshare.install "build"
  end

  def post_install
    fig_dir = File.expand_path("~/.fig/autocomplete")
    target = File.join(fig_dir, "build")
    FileUtils.mkdir_p(fig_dir)
    if File.directory?(target) && !File.symlink?(target)
      backup = "#{target}.backup-#{Time.now.strftime("%Y%m%d%H%M%S")}"
      FileUtils.mv(target, backup)
      opoo "Existing #{target} moved to #{backup}"
    end
    FileUtils.ln_sf(opt_pkgshare/"build", target)
  end

  def caveats
    <<~EOS
      Completion specs are symlinked for Kiro CLI:
        ~/.fig/autocomplete/build -> #{opt_pkgshare}/build
      They update automatically on \\\`brew upgrade\\\`.
    EOS
  end

  test do
    assert_path_exists pkgshare/"build/kubectl.js"
  end
end
`;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const [version, sha256] = process.argv.slice(2);
  if (!version || !sha256) {
    console.error("Usage: generate-formula.mjs <version> <sha256>");
    process.exit(1);
  }
  process.stdout.write(generateFormula(version, sha256));
}
