#!/usr/bin/env node
// Generates Formula/autocomplete-specs.rb for Okabe-Junya/homebrew-tap.
// Usage: node scripts/generate-formula.mjs <version> <sha256>

export function generateFormula(version, sha256) {
  return `# typed: false
# frozen_string_literal: true

# This file is generated by Okabe-Junya/autocomplete's release workflow. DO NOT EDIT.
class AutocompleteSpecs < Formula
  desc "Prebuilt completion specs for Kiro CLI autocomplete"
  homepage "https://github.com/Okabe-Junya/autocomplete"
  url "https://github.com/Okabe-Junya/autocomplete/releases/download/v${version}/autocomplete-specs-${version}.tar.gz"
  sha256 "${sha256}"
  version "${version}"
  license "MIT"

  def install
    # The tarball's single top-level "build/" directory is stripped by
    # Homebrew's staging, so the specs land directly in the buildpath.
    (pkgshare/"build").install Dir["*"]
  end

  def caveats
    # post_install cannot create this symlink: Homebrew sandboxes it with a
    # redirected HOME, so writes to "~" silently land in a throwaway dir.
    <<~EOS
      To let Kiro CLI load these specs, create a one-time symlink
      (move any existing real directory aside first):
        mkdir -p ~/.fig/autocomplete
        ln -sfn #{opt_pkgshare}/build ~/.fig/autocomplete/build
      The link target is stable, so future \\\`brew upgrade\\\`s apply automatically.
    EOS
  end

  test do
    assert_path_exists pkgshare/"build/kubectl.js"
  end
end
`;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const [version, sha256] = process.argv.slice(2);
  if (!version || !sha256) {
    console.error("Usage: generate-formula.mjs <version> <sha256>");
    process.exit(1);
  }
  process.stdout.write(generateFormula(version, sha256));
}
